name: automated release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

permissions:
  contents: write

jobs:
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: download mpv
        run: |
          echo api=$(curl \"https://api.github.com/repos/shinchiro/mpv-winbuild-cmake/releases/latest\" | python -c \"import sys, json; print(json.load(sys.stdin)['assets'][9]['browser_download_url'])\") >> $GITHUB_ENV
          curl $api -o mpv.7z
          7z x mpv.7z -ompv/
          
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.tag }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="autobloom v${tag}" \
              --generate-notes
