name: automated release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

permissions:
  contents: write

jobs:
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.tag }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="autobloom v${tag}" \
              --generate-notes
